### ISSUE TITLE
代码调试疑问

### ISSUE THREAD

**Issue by YinhuiLe-Git** [qinguoyi/TinyWebServer#6]
你好，我最近在阅读调试源码时，在Ubuntu中进行make时，系统报错   ：在http_conn.cpp文件中第549行，temp=writev(m_sockfd,m_iv,m_iv_count); writev函数并没有在此文件中定义，所以make失败了，烦请大佬解释一波，不甚感激！

**Comment by zjuHong** [comment]
我之前也遇到过这个问题，你在头部引用sys/uio.h即可



发自我的小米手机在 YinhuiLe-Git <notifications@github.com>，2020年3月29日 18:21写道：

你好，我最近在阅读调试源码时，在Ubuntu中进行make时，系统报错   ：在http_conn.cpp文件中第549行，temp=writev(m_sockfd,m_iv,m_iv_count); writev函数并没有在此文件中定义，所以make失败了，烦请大佬解释一波，不甚感激！



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/qinguoyi/TinyWebServer/issues/6",

"url": "https://github.com/qinguoyi/TinyWebServer/issues/6",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
